# Generated by Django 5.0 on 2023-12-25 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofiles',
            name='city',
        ),
        migrations.AddField(
            model_name='userprofiles',
            name='customer_omise_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofiles',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofiles',
            name='profile',
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofiles',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofiles',
            name='first_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='userprofiles',
            name='last_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='userprofiles',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
