# Generated by Django 5.0 on 2023-12-25 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_userprofiles_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofiles',
            name='username',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
