# Generated by Django 5.0.2 on 2024-02-08 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='total',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
